#!/bin/bash
IP=$1
scp puppet.tgz $IP:
ssh $IP 'test -d puppet || mkdir puppet'
ssh $IP 'tar zxvf puppet.tgz -C puppet'
ssh $IP 'cd puppet && sudo ./bin/puppet apply --modulepath=modules:vendor/modules --hiera_config=hiera_production.yaml --environment=production manifests/site.pp'
